### ISSUE TITLE
iterations of cdac_sla for DomainNet

### ISSUE THREAD

**Issue by Amos1109** [chu0802/SLA#10]
Thanks for your great work! But I have a question, i want to know the iterations of cdac_sla for DomainNet, because in your paper, the **warmup iteration** is 50000.

**Comment by chu0802** [comment]
Thanks for raising the issue.

Indeed, that is the number of warm-up iterations we use when fine-tuning the model with CDAC + SLA. Empirically, we found that CDAC + SLA performs better, especially when CDAC converges to an optimal point. (On the other hand, MME + SLA yields the opposite result.)

**Comment by Amos1109** [comment]
> Thanks for raising the issue.
> 
> Indeed, that is the number of warm-up iterations we use when fine-tuning the model with CDAC + SLA. Empirically, we found that CDAC + SLA performs better, especially when CDAC converges to an optimal point. (On the other hand, MME + SLA yields the opposite result.)
Thanks for reply! So what's the total number of iterations?

**Comment by Amos1109** [comment]
> Thanks for raising the issue.
> 
> Indeed, that is the number of warm-up iterations we use when fine-tuning the model with CDAC + SLA. Empirically, we found that CDAC + SLA performs better, especially when CDAC converges to an optimal point. (On the other hand, MME + SLA yields the opposite result.)

Thanks for reply! So SLA needs more iterations (more than 50,000)?

**Comment by chu0802** [comment]
Yes, in our experiment, when using CDAC + SLA on DomainNet, we tuned it for 100,000 iterations. (50,000 for warmup, 50,000 using SLA)
