### ISSUE TITLE
The derivation of the ideal centers

### ISSUE THREAD

**Issue by MyTuring** [chu0802/SLA#11]
Hello, there is just a sentence in this process.  Could you give the detail, please?

**Comment by chu0802** [comment]
Hi, thanks for your question.

A center is a representative point for a cluster in a certain feature space. The best clusters should be based on the labels of the data itself. In this case, the ideal center should be the average of all data points with the same labels.

However, the ideal case is not accessible in practice. Thus, we develop a pseudo-label mechanism (PPC) to approximate the ideal case.

Let me know if you have any further questions!

**Comment by MyTuring** [comment]
Thank you for your response. But I am confused by the Table 3. Can the PPC calculate the ideal centers? If it can't, how could I calculate the distance between others centers and the ideal centers?

**Comment by chu0802** [comment]
We are not using PPC to calculate ideal centers. PPC is a protonet, a protonet can be equipped with diferent centers.
Empirically we found the centers with pseudo-labels are much closer to the ideal centers compare with few-shot target centers.

**Comment by MyTuring** [comment]
I am sorry. I have read the paper again. And I have gotten what you said. But I am still confused by the calculating of the ideal centers without the unlabeled target dataset. "The ideal centers should be derived through the unlabeled target dataset", Idon't have the y, how can I know which class the center belongs to?

**Comment by chu0802** [comment]
Yes, we have no access to the unlabeled target dataset. Thus, this is an "ideal case". Practically we need to approximate the ideal case, and we develop a pseudo-label mechanism to do so.

**Comment by MyTuring** [comment]
Well, I've got the main idea. Thank you for your reply.

**Comment by MyTuring** [comment]
Well, I've got the main idea. Thank you for your reply
