### ISSUE TITLE
No CUDA GPUs are available - environment.yaml

### ISSUE THREAD

**Issue by rashmi-ss** [chu0802/SLA#13]
Hello, 
I am trying to set up my anaconda environment to run the SLA code but I am facing some challenges-
1. I have tried with requirements.txt earlier but there was error - RuntimeError: No CUDA GPUs are available
2.  I have tried with environment.yaml but still there is error - RuntimeError: No CUDA GPUs are available
3. I do have Nvidia GPU available in my computer and it works fine for other anaconda projects where GPU is needed. When I run these commands in the newly created environment, I get these results-
>>> torch.__version__
'2.0.0'
>>> print(torch.cuda.is_available())
True
>>> torch.cuda.get_device_properties(0)
_CudaDeviceProperties(name='NVIDIA GeForce RTX 2060', major=7, minor=5, total_memory=6143MB, multi_processor_count=30)
4. Operating System is Windows 11 
5. Since, some of the dependencies were not resolved from environment.yaml, I had to comment those before creating environment. Please refer the attached file 'environment_yaml.txt' (changed the name and type as .yaml was not getting attached here).
[environment_yaml.txt](https://github.com/chu0802/SLA/files/14731318/environment_yaml.txt)

Could you please help to resolve this issue?

**Comment by rashmi-ss** [comment]
The issue is finally resolved after following these-

1. conda create -n sla_env python=3.10.10
conda activate sla_env 
2. pip install -r requirements.txt
[requirements.txt](https://github.com/chu0802/SLA/files/14766820/requirements.txt)
3. Installed torch and cuda
pip install torch==1.12.0+cu116 torchvision==0.13.0+cu116 torchaudio==0.12.0 --extra-index-url https://download.pytorch.org/whl/cu116

**Comment by chu0802** [comment]
Thanks for your help for figuring out the best way to build the environment! I will update the instruction for installation accordingly.
