### ISSUE TITLE
Regarding Office31

### ISSUE THREAD

**Issue by gitmate21** [chu0802/SLA#14]
does your code prepares dataset for Office31 ??

What necessary changes should i make if i want to download and prepare it??

Thanks for your help and consideration.

**Comment by chu0802** [comment]
Hi, thanks for raising the issue.

Currently, our code does not support evaluation on the Office31 dataset. While it is technically feasible to implement, we have not tested it thoroughly and thus do not plan to add this feature in the future.
 
However, if you would like to add this feature based on this code base, here are some high-level steps to get you started:

(0). Download the dataset and organize it in the following structure:
```
- dataset_dir
    - dataset_name
        - domain 1
        - ...
        - domain N
        - text
            - domain 1
                - all.txt
                - train_1.txt
                - train_3.txt
                - test_1.txt
                - test_3.txt
                - val.txt
            - ...
            - domain N
    - ...
 ```
You can obtain the necessary text files from the MME project.

(1). Modifying the dataset config in `data_preparation/dataset.yaml`.

(2). Turning the dataset to `Office31` in `config.yaml`, and specifying appropriate hyper-parameters (note that we have not explored these thoroughly for Office31).

Hope this helps!
