### ISSUE TITLE
Unable to Run the Code for the Dataset of DomainNet 

### ISSUE THREAD

**Issue by Tharun19r** [chu0802/SLA#15]
We have Successfully Run the code for the OfficeHome But while coming to the dataset of the DomainNet we are not the results. It has been showing the No such File [ FileNotFoundError: [Errno 2] No such file or directory: '/DATA2/dse316/grp_010/github_code/DomainNet/clipart/teddy-bear/clipart_304_000053.jpg' ].

We have been updated the config paths in yaml file

**Comment by chu0802** [comment]
Thanks for raising the issue. After checking the official links for DomainNet data provided [here](http://ai.bu.edu/M3SDA/), I have noticed that the current links for downloading Clipart and Painting datasets provided in my script are incorrect. I have updated the correct links in my script. You can download Clipart and Painting datasets manually via the following links:
* Clipart: http://csr.bu.edu/ftp/visda/2019/multi-source/groundtruth/clipart.zip
* Painting: http://csr.bu.edu/ftp/visda/2019/multi-source/groundtruth/painting.zip

Feel free to have any other questions, thanks!
