### ISSUE TITLE
Can you provide a checkpoint?

### ISSUE THREAD

**Issue by asher-bit** [chu0802/SLA#16]
Hello, thank you very much for your excellent work! Can you provide some checkpoints for testing?

**Comment by chu0802** [comment]
Thank you for your interest and kind words!

Unfortunately, this project was released over a year ago, and we did not preserve the original checkpoints. Currently, there are no plans to re-train the model and release new checkpoints.

However, based on my experience, it should be easy to reproduce the results. Training the model on the Office-Home dataset typically takes less than 30 minutes. Though it takes longer time to reproduce the results for Domain-Net, it should not be longer than half a day.

Feel free to raise other issues if you encounter problems when reproducing the results, thanks!
