### ISSUE TITLE
KeyError when running main.py :'ResNet34_Weights'

### ISSUE THREAD

**Issue by ghqshuai** [chu0802/SLA#9]
Hello, when running the main program, a problem 'KeyError: 'ResNet34_Weights'' is displayed on line 96 of the model file. It seems that the key does not exist in the dictionary or module, can you tell me how to solve it? Thank you.

**Comment by chu0802** [comment]
Hi, thanks for raise the issue.
I have confirmed that in torchvision version 0.15, the key `"ResNet34_Weights"` should be present in `torchvision.models`.

You can verify this using the following Python code:
```python
from torchvision import models

"ResNet34_Weights" in models.__dict__
```
Output:
```
True
```

Please double-check that the version of your torchvision is version 0.15.

reference: [torchvision ver. 0.15](https://pytorch.org/vision/0.15/_modules/torchvision/models/resnet.html#ResNet34_Weights).

**Comment by ghqshuai** [comment]
Ok, thank you for your reply
